### ISSUE TITLE
Extreme increase of size of this library

### ISSUE THREAD

**Issue by silvanverschuur** [elax46/custom-brand-icons#166]
I'm using this great icon library for a while now in my Home Assistant installation. A couple of months ago some icons were added that made this library extremely huge. One of these icons is 1.6 MB! 

In my opinion it's good practice to keep icons small (a couple of kb's) so the overall loading time will not be affected that much.

**Comment by elax46** [comment]
Thank you for igniting the discussion on the subject. Could you tell me what the icons are, thanks

**Comment by silvanverschuur** [comment]
Thanks, that would be great. Your list contains all icons that could be reduced (especially sonos-arc/sonos-one). I don't have any graphical skills so maybe someone else can help?

**Comment by elax46** [comment]
> Thanks, that would be great. Your list contains all icons that could be reduced (especially sonos-arc/sonos-one). I don't have any graphical skills so maybe someone else can help?

see me and @rchiileea  to reduce the larger ones shortly then slowly try to align them all on 4kb / 2kb

**Comment by rchiileea** [comment]
if I reduce them they will loose the 3d effect completely (for example the sonos ones would loose the speak grill effect.

**Comment by rchiileea** [comment]
I still dont see a valid argument for reduction, my automations are what take the longest on boot not any of the hacs icons, when ha boots, the icons are showing on dash before the mqtt connects up and I am only using icons from this repo.

**Comment by silvanverschuur** [comment]
Your browser has to download and execute a 3.18MB file and keep it in memory. That's the reason to aim for smaller Javascript files. Besides that, this is an icon library. An icon with a size of approximately 32x32 pixels shouldn't be 1.6MB if you ask me. That's almost the size of a fullscreen web image.

**Comment by rchiileea** [comment]
browsers on initial cache have to d/l this once, the thing is, we have moved way beyond 56k dial ups, you need to provide a better explination, firrst we were pointing out the some real reasons to convince me its too much, if we are talking apps on phones we are still talking a matter of seconds. the only solution I would see is to go back to full flat icons again, the speaker grill ones will always be larger for that and most of the 3d effect ones will be too, just because of all the extra line work involved.

m,y point is that first saying "In my opinion it's good practice to keep icons small (a couple of kb's) so the overall loading time will not be affected that much." which is not effected the ha loading at all, then saying browser issue, well for pc's even a 500kb connection would still load these instantly, it would be like saying that we should remove camera feeds from HA because 1080p will use more size too.

**Comment by elax46** [comment]
@silvanverschuur now released a [pre-version](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.59b1) with a reduction of -34.906% on the library

**Comment by silvanverschuur** [comment]
@elax46 That's great news! I have also checked some online SVG compressors and this [one](https://vecta.io/nano) has good results. Especially the `garage-<number>-prong.svg` files can be compressed by 30% without visible loss. Maybe it is any idea to try this compressor with some of the largest files?

**Comment by elax46** [comment]
@rchiileea suggested [this](https://compress-or-die.com/svg)but I will also try this to see if there is a further reduction

**Comment by elax46** [comment]
> @elax46 That's great news! I have also checked some online SVG compressors and this [one](https://vecta.io/nano) has good results. Especially the `garage-<number>-prong.svg` files can be compressed by 30% without visible loss. Maybe it is any idea to try this compressor with some of the largest files?

If you can check if there has been an improvement with the beta version thanks

**Comment by silvanverschuur** [comment]
@elax46 I have done some quick performance test and it transfer and processing time are improved by roughly 30%. I didn't look at memory usage but I'm sure that's it's also affected by this reduction.

**Comment by elax46** [comment]
@silvanverschuur Thanks for your feedback I will continue to further reduce the size of the library

**Comment by elax46** [comment]
@silvanverschuur [further reduction](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.59b2)
