### ISSUE TITLE
Don't steal others work.

### ISSUE THREAD

**Issue by arallsopp** [elax46/custom-brand-icons#30]
Please remove the icons I have created from your repo immediately. Almost half of your repo are works directly stolen from https://github.com/arallsopp/hass-hue-icons 

- You do not have permission to distribute my original works.
- You are violating the creative commons license.
- Passing other peoples work off as your own is disingenous and damaging to the community.
- Accepting credit and putting your paypal link on a release that I created for free is fraudulent.

I am sure this was an oversight. You have contributed to other projects, and doubtless know the time and effort it takes to bring something to fruition. I am sure you can recognise the many hours I have spent designing the 80 or so icons for our home assistant community, and know the satisfaction earned through doing a job well and honestly.

I drew these icons in response to community requests, and they exist nowhere else. I am confident you are familiar with my icon request template, and so will know the conversations that document their creation, the original contributors, our design work and resolution.

**Please now remove the icons, and desist from following my releases and bundling my original works into your repo.**

For avoidance of doubt, all of my hue icons are on 24x24 grids, and so should be easy to locate as belonging outside the hue developer pack. These were created by me for the community and are not for distribution without permission. If you need further detail, come by my repository. I took the time to attribute the hue developer pack icons and separate them from the works I've created in response to community requests: https://github.com/arallsopp/hass-hue-icons#user-requested-hue-icons 

Lastly, your existing installation base may miss my icons when you remove them. If you care to help them, please add a link explaining that those icons remain available for free at their original repo : https://github.com/arallsopp/hass-hue-icons. 

I hope that we have a happy future contributing alongside each other to support the home assistant community.

**Comment by elax46** [comment]
Hi I was already proceeding to the correct attribution of your icons but I think it is also fair to say that you could have collaborated in the inclusion of other icons in this repo rather than create a duplicate considering that I have been carrying out the latter for more than three months and yours has been available for less than a month. Before opening mine I checked that there were no others but I don't think you did. In this way you have also thwarted my attempt to contribute to the community by creating a copy of a repo that has the same purpose. You could have asked me to cooperate and I would have been very happy to change the license and remove contributions. Having said that I respect your work without problems so I will change the license and give the right credit to your work but I will continue to distribute your icons by also eliminating my paypal references without problems.

**Comment by arallsopp** [comment]
...and also by eliminating [issue 29](https://github.com/elax46/custom-brand-icons/issues/29), in which you took credit and payment for an icon that you knowingly stole from my repo? I am sure you did that in a spirit of cooperation and for the betterment of the community.

Well.. Let's leave it there. No point in arguing on the internet, after all. I hope you go on to make contributions of your own, and that you gain some satisfaction.

**Comment by elax46** [comment]
I have not taken any contributions for the icons made. The user wrote and I thanked me even though I did not receive anything and I did not cancel anything. I respect your work but I repeat if you wanted to have a spirit of collaboration you should not have opened another repo identical to this one but you could easily collaborate as I myself have done in other projects. Having said that peace and love but next time before opening a repo look if there is already one and if you want to contribute do it without creating copies

**Comment by elax46** [comment]
I have not made any contributions for the icons you made. The user wrote to me and thanked me in advance even if I have not received anything or demanded anything. I respect your work but I repeat if you wanted to have a spirit of collaboration you should not have opened another repo identical to this one but you could easily collaborate as I did in other projects. Having said that peace and love but next time before opening a repo look if there is already one and if you want to contribute do it without creating copies this kills the real collaboration and makes everyone's work useless, even discrediting it. I canceled the user's request because it was disrespectful to write that comment you could discuss it first (I have no problem proving that I have not received anything).
![Cattura-3](https://user-images.githubusercontent.com/55278049/129585283-488c1d24-3719-4021-a7c5-07f80063b498.JPG)
I added your references and your terms and conditions certainly not for money but next time collaborate don't be individualistic
