### ISSUE TITLE
Why this repo, and not credit the work of @arallsopp?

### ISSUE THREAD

**Issue by Mariusthvdb** [elax46/custom-brand-icons#31]
Hi,

writing here, since at https://github.com/arallsopp/hass-hue-icons, @arallsopp has offered the community many Hue icons he created, and hasn't stopped updating those upon request, with almost daily new additions to that resource.

Wouldn't it be fair to use that repo, and, if you have very specific reason not to do that, at least credit his work, and take up some communication, asking him if it's alright you would copy all of that?

I feel it would, and hope you do too, all in the spirit of recognizing the methods in the open source world, giving credit where credit is du. So we can all benefit, and enjoy building it forward, together.

**Comment by elax46** [comment]
Dear, this repo was born three months before the one you indicated and its material is mentioned so I don't see what the reason for this useless request is. I do not accept that it is said "because this repo exists it is a copy of another" This repo was born on May 14, 2021. Ask the other creator why he did not collaborate in this rather than open his own. It would have been easy to write to me and he could have collaborated on the latter without problems but it did not happen. Let's verify the information before writing randomly

**Comment by Mariusthvdb** [comment]
well I guess this quote of yours says it all:

> I will continue to distribute your icons

https://github.com/elax46/custom-brand-icons/issues/30#issuecomment-899531014

no matter the age of the repo I would think.

**Comment by elax46** [comment]
well then what would be the problem?  the quote is present and the [distribution license is the same](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en)
