### ISSUE TITLE
well then what would be the problem? 

### ISSUE THREAD

**Issue by Mariusthvdb** [elax46/custom-brand-icons#32]
well then what would be the problem?  the quote is present and the [distribution license is the same](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en)

_Originally posted by @elax46 in https://github.com/elax46/custom-brand-icons/issues/31#issuecomment-899839556_

sorry to open a new issue, but you closed the previous one while asking me a question.

the problem: even the Creative Commons indicate you should at least mention if you copied the material, or if you changed anything in the material. Next to crediting that is.

Since you copied the other authors Hue icons, without mentioning you didn't change them,  you seem to not abide by that set of common courtesy rules/license terms.

Why not simply leave out the Hue icons, and create your own set of brand icons ion this case? No harm done, and credit where credit is due.

**Comment by elax46** [comment]
I still do not understand why you want to make the controversy.  although the content is the same I mentioned the author!  the matter ends here.  although the age of the repo does not count but you don't think it was more right to collaborate rather than create an identical integration?  the real point of the matter is this.  The question why you did not collaborate is not answered!
