### ISSUE TITLE
Custom Icon request [BE channels]

### ISSUE THREAD

**Issue by jrspowers** [elax46/custom-brand-icons#363]
hello is it possible to add these belgium channels in this folder below they are? 
all thanks in advance! 

[logo](https://mega.nz/folder/Dxw2hLZI#VaA7fxxmKzYDKExN3lDjsQ)

**Comment by rchiileea** [comment]
going further down this route of channels and individual channels or programs I think we need to slow down on to avoid over weight of the repo, the file is already very large and if we keep accepting request for all channels and all shows we will end up with more of those that actual items.... sorry, reduce this list to ones that have apps (for example vtm would full under all the vtm ones and you could add a title under each one to indicate the individual channel. I can reduce the square size to rectangle so it has more room if you wish.

**Comment by jrspowers** [comment]
So if I understand correctly you don't want to do it, very unfortunate

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/224972081-c0656e19-777f-4bef-9d4a-9cfe9d9b8bb3.png)
I have done a vtm alt for you so that its not as large (you can then add titles or custom text to card to indacate which one its is, you have to see the point doing multiple of one service could end up being crazy... (sky for instance, skysports 1, skysports 2 skysports 3, skysports premier league, skysports f1, sky sports golf, skysports news ect ect) it would end up being a channel repo more than a brand repo.

**Comment by jrspowers** [comment]
okay thanks but then I have a question, can you still add the logo of go_play & big_brother wall these are not a channel but an app?  then I have a question you made vtm go as a logo but the go is not there do you also want to adjust it & you can find the 3 logo above in the link?  thanks in advance!

**Comment by rchiileea** [comment]
create a new post for them I will take a look in next round of logos to be done so its not muddled in this round.

**Comment by jrspowers** [comment]
I have submitted a new request
