### ISSUE TITLE
Custom Icon request - Ikea Ramsele

### ISSUE THREAD

**Issue by mtjoernelund** [elax46/custom-brand-icons#767]
Love the speecific icons. Really awesome work. Any chance that you could do the Ikea Ramsele lamp as well?

![IMG_0714](https://github.com/user-attachments/assets/ad7fef4a-986c-4228-94a7-a4d7abdcec7f)

**Comment by rchiileea** [comment]
that would be a lot of work to create that, would take over a hour of tracing.

**Comment by mtjoernelund** [comment]
Understood. Would love to contribute myself, but have no idea where to start and have very little drawing skills.

**Comment by rchiileea** [comment]
I understand, but I dont mind doing items that take 10 to 15 minutes on lunch break, but stuff thats going to take me over a hour too do would cost me valuble time, as you may of noticed I am not updating logos as much as I used to because of working more. so only have time to do in lunch breaks now.
